### ISSUE TITLE
When importing resources between CKAN instances, url is not preserved if url_type='upload'

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/ckanapi#41]
Reproducing:
1. Create a dataset on CKAN1, uploading a file for a resource
2. Import this dataset into CKAN2:

```
ckan1 = ckanapi.RemoteCKAN('http://ckan1.org', apikey=...)
ckan2 = ckanapi.RemoteCKAN('http://ckan2.org, apikey=...)

package = ckan1.action.package_show(id='package1')
ckan2.action.package_create(**package)
```

Expected result should be that, either:
a. The dataset will be migrated, along with it's resource files
b. The dataset metadata will be migrated, with the resource file links still pointing to CKAN1

Instead, uploaded resource files are not migrated but their url bases are changed to http://ckan2.org instead of http://ckan1.org

This happens when `resource['url_type']` is set to upload. The bug can be fixed by migrating the dataset like so:

```
for res in package['resources']:
  res.pop('url_type')

ckan2.action.package_create(**package)
```

I am not sure whether this is a CKAN issue, or a ckanapi issue, so I'm filing it here. The relevant code in CKAN is [here](https://github.com/ckan/ckan/blob/3980a5728b6330728213a6be9b4db39fa78cf87f/ckan/lib/dictization/model_dictize.py#L118).

Another thing to note, which does seem to be a CKAN bug, is that the resource is saved in the database with it's proper url - pointing to http://ckan1.org. It is only indexed in Solr with the wrong url.

**Comment by deniszgonjanin** [comment]
Another effect of this bug is that it is impossible to change the url of a resource when it's `url_type` is set to `upload`. For example, this code does nothing when a resource `url_type == 'upload'`:
```
ckan.action.resource_update(id='id', url='http://example.com')
```

**Comment by perceptron-XYZ** [comment]
It is a CKAN issue. Whenever 'url_type' is set to 'upload', their code (as per @deniszgonjanin referenced) will call routes.url_for to rebuild the url.
```
resource['url'] = h.url_for(controller='package',
                                    action='resource_download',
                                    id=resource['package_id'],
                                    resource_id=res.id,
                                    filename=cleaned_name,
                                    qualified=True)
```
This process will wrap the rest of the url with local hostname so files from another host will also be changed into the localhost.
The easiest solution would be to pop 'url_type' for external resources, since they are not uploaded files in the first place.  i.e
```
url  = resource['url']
host = urlparse.urlparse(url).hostname
if host != None:
        resource.pop['url_type']

if resource.get('url_type') == 'upload' and not context.get('for_edit'):
        cleaned_name = munge.munge_filename(url)
        resource['url'] = h.url_for(host=host,
                                    controller='package',
                                    action='resource_download',
                                    id=resource['package_id'],
                                    resource_id=res.id,
                                    filename=cleaned_name,
                                    qualified=True)
```
But since we are considering this issue in ckanapi now, I suggest not change CKAN's code for now.

**Comment by wardi** [comment]
@perceptron-XYZ was this fixed by #65 ?

**Comment by perceptron-XYZ** [comment]
Yes, it's fixed by --resources option.

**Comment by LingboTang** [comment]
I have similar problems in my project. Basically I want to copy/clone package including both metadata and resources attached to it. With the following code, I was able to copy package metadata and resources successfully to the new package. But the original package will lose its resources because now these resources are referenced to the new package. I would like to know a way that I can maintain the resources for the original package.

```
pkg = toolkit.get_action('package_show')(None, dict(id=id))
action = toolkit.get_action('package_create')
newpkg = action(context, pkg)
```
