### ISSUE TITLE
Running actions fails with missing dependencies

### ISSUE THREAD

**Issue by miraculixx** [ckan/ckanapi#75]
I installed the ckanapi package as follows

```
$ pip install ckanapi
```

Running the `package_list` action fails as follows. Note this is a remote ckan instance that I'm accessing as a user. I don't want to install or run a ckan server locally:

```
$ ckanapi action package_list http://ckanhost/api
Traceback (most recent call last):
(...)
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PasteScript
```

Installing `PasteScript` reveals a further depencency on `ckan` itself:

```
$ pip install PasteScript
$ ckanapi action package_list http://ckanhost/api
Traceback (most recent call last):
  File ".virtualenvs/geops/local/lib/python2.7/site-packages/ckanapi/cli/paster.py", line 2, in <module>
    from ckan.lib.cli import CkanCommand
ImportError: No module named ckan.lib.cli
```

I did continue installing ckan, which however requires to pull in more and more dependencies, eventually rending up with a pylon import error:

```
$ <lots of pip install's>
$ ckanapi action package_list http://ckanhost/api
    from pylons import g, c, request, session, response
ImportError: cannot import name g
```

IMHO one should not be required to install the server (AFAIK that's what the ckan package provides, if I'm not mistaken) just to use the API client.

What am I missing?

**Comment by wardi** [comment]
`-r` lets you connect to remote ckan instances which requires no additional libraries

**Comment by miraculixx** [comment]
I managed to get over the pylons import error by installing `Pylons==0.9`. Unfortunately, the troubles continue:

```
$  ckanapi action package_list -r http://ckanhost/api
(...)
  File "./virtualenvs/geops/local/lib/python2.7/site-packages/ckan/model/meta.py", line 25, in __init__
    self.use_redis = asbool(config.get('ckan.page_cache_enabled'))
AttributeError: 'module' object has no attribute 'get'
``` 

Note that even calling `ckanapi -h` results in the same error. It is due to this [import](https://github.com/ckan/ckanapi/blob/master/ckanapi/errors.py#L30). What is the rationale of the `ckan` (server) module being a pre-requisite of the API?

**Comment by wardi** [comment]
Do you have a ckan.py file in the same directory that you're running ckanapi by any chance?

**Comment by wardi** [comment]
ckan is not a pre-requisite of ckanapi. ckanapi will look for ckan and if it can import it so that local ckan commands may be issued (calling ckan actions directly instead of through the HTTP API).

I suspect that in your environment you either have a copy of ckan without the dependencies or something that is importable as "ckan" but isn't the real ckan.

**Comment by jackmaney** [comment]
I've run into prettymuch the exact same issues, and I have no namespace conflicts with `ckan`. Can we please get an up-to-date list of requirements in `requirements.txt`?

In particular, `PasteScript`, `ckan.lib.cli`, and `formencode.validators` were all named in `ImportError`s when trying to do the following (slightly anonymized, since I'm at work):

    ckanapi action package_show -r http://company.ckan.domain:port/ id=some-id

**Comment by wardi** [comment]
none of those things are required by the command you're running.

What I think's happening (best guess, you provided no traceback) is your python interpreter thinks it can import ckan so ckanapi tries to to give you access to the LocalCKAN functionality, but your ckan installation is broken due to missing dependencies. Try running "import ckan" at a python prompt and I expect you'll see the same errors.

If so, try `pip unsitall ckan` and run your command again.

**Comment by Br3nda** [comment]
I just hit this too.

It seems, if you have ckan installed by pip (and importable at run time), you can't even run `--help` without hitting exception throws about missing dependencies, or if you're in a recent python version, the old python 2.7 syntax for exception catching etc.

I solved by running `pip uninstall ckan` like @wardi said, and then it runs happily in python3.5.
